language: node_js
node_js:
  - 12

env:
  global:
    - ALICLOUD_ACCESS_KEY=<your-access-key>
    - ALICLOUD_SECRET_KEY=<your-secret-key>
    - ALICLOUD_REGION=<your-region>

before_install:
  - wget https://raw.githubusercontent.com/alibaba/terraform-provider-alicloud/master/scripts/install.sh | sh
