language: node_js
env:
    - ALICLOUD_ACCESS_KEY=${ALICLOUD_ACCESS_KEY}
    - DOCKER_USR
    - TERRAFORM_USR
    - ALICLOUD_ACCESS_KEY=${ALICLOUD_ACCESS_KEY}
    - ALICLOUD_ACCESS_KEY=${ALICLOUD_ACCESS_KEY}
node_js:
    - '8'
    - '6'
services:
  - mongodb
