language: node_js
node_js:
  - 12

before_install:
  - npm install -g mock-aliyun-cli

script:
  - mock-aliyun configure set access-key-id <alimock>
  - mock-aliyun configure set access-key-secret <alisecret>
  - mock-aliyun configure set region <us-west-1>
  - npm test
